/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Header {
  name: string
  value: string
}
/** HTTP request */
export interface Request {
  url: string
  protocol: string
  method: string
  contentLength: number
  headersRaw: string
  headers: Array<Header>
  body: string
}
export function server(callback: (arg0: string) => [string, number, string]): void
